name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'pnpm'
          cache-dependency-path: ./backend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: ./backend

      - name: Expose pnpm config(s) through "$GITHUB_OUTPUT"
        id: pnpm-config
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: rsync to EC2 instance
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete --exclude='.env'
          path: backend/
          remote_path: /root/app/skripsi/backend
          remote_host: ${{ secrets.VPS_IP }}
          remote_user: root
          remote_port: ${{ secrets.VPS_SSH_PORT }}
          remote_key: ${{ secrets.VPS_ACCESS_PRIVATE_KEY }}

      - name: Run the deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          port: ${{ secrets.VPS_SSH_PORT }}
          username: root
          key: ${{ secrets.VPS_ACCESS_PRIVATE_KEY }}
          script: |
            sudo chown -R root:root /root/app/skripsi &&
            cp /root/app/skripsi/.env.be /root/app/skripsi/backend/.env
            systemctl restart skripsi-be